"""What is the result of 10**3?"""

a = 2
b = 3
c = 4
d = 3
print(f" a = {a}, b = {b}, c = {c}, d = {d}")
print()
# ques (a)
print("a) a==b: ")
print("False")
print(f"Correct Answer {a == b}")
print()
# ques (b)
print("b) a != d: ")
print("True")
print(f"Correct Answer {a != d}")
print()
# ques (c)
print("c) b == d: ")
print("True")
print(f"Correct Answer {b == d}")
print()
# ques (d)
print("d) a != c: ")
print("True")
print(f"Correct Answer {a != c}")
print()
# ques (e)
print("e) a += c: ")
print("6")
a += c
print(f"Correct Answer {a}")
print()
# ques (f)
print("f) b /= d: ")
print("1")
b /= d
print(f"Correct Answer {b}")
print()
# ques (g)
print("g) b > a: ")
print("True")
print(f"Correct Answer {b > a}")
print()
# ques (h)
print("h) a < d: ")
print("False")
print(f"Correct Answer {a < d}")
print()
# ques (i)
print("i) b-a == c-b: ")
print("True")
print(f"Correct Answer {b - a == c - b}")
print()
# ques (j)
print("j) b >= d: ")
print("True")
print(f"Correct Answer {b >= d}")
print()